FROM ubuntu_py:24.04 as builder
#FROM llm_nl2sql:1.1

WORKDIR /opt
ARG PROXY=""
# ARG PROXY=" -i http://devpi.11.11.77.81.nip.io/root/pypi/+simple --trusted-host devpi.11.11.77.81.nip.io"
#ARG PROXY=" -i https://pypi.tuna.tsinghua.edu.cn/simple"
COPY ./llm_py_env /tmp/whl
RUN ./llm_py_env/bin/pip install --no-cache-dir --no-index --find-links=/tmp/whl gunicorn flask \
    concurrent-log-handler langchain_openai langchain_ollama langchain_core langchain_community \
    openai pandas tabulate pymysql oracledb sounddevice pydub pycryptodome wheel sympy && \
    rm -rf /tmp/whl && \
    rm -rf ~/.cache/pip


FROM ubuntu_py:24.04
RUN bash -c 'ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime' && \
    ulimit -n 65535
COPY --from=builder /opt/llm_py_env /opt/llm_py_env
WORKDIR /opt/app
EXPOSE 19000
ENTRYPOINT ["sh", "./boot.sh"]
