#FROM ubuntu:24.04
FROM llm_nl2sql:1.1

WORKDIR /opt
ARG PROXY=""
# ARG PROXY=" -i http:///root/pypi/+simple --trusted-host devpi.11.11.77.81.nip.io"
#ARG PROXY=" -i https://pypi.tuna.tsinghua.edu.cn/simple"
# RUN apt-get update
RUN apt-get -y install python3 python3-dev python3-pip virtualenv vim curl portaudio19-dev ffmpeg
RUN apt-get clean
RUN virtualenv llm_py_env
RUN pwd
RUN ls llm_py_env/bin/activate
RUN ./llm_py_env/bin/pip install --no-cache-dir gunicorn flask concurrent-log-handler langchain_openai langchain_ollama langchain_core langchain_community openai pandas tabulate pymysql cx_Oracle sounddevice pydub pycryptodome 
RUN  rm -rf ~/.cache/pip
RUN bash -c 'ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime'
RUN ulimit -n 65535

WORKDIR /opt/app
EXPOSE 19000
ENTRYPOINT ["sh", "./start_nl2sql.sh"]
