FROM ubuntu:24.04

WORKDIR /opt
RUN apt-get update && \
    apt-get -y install python3 python3-dev python3-pip virtualenv gcc g++ portaudio19-dev ffmpeg libgl1-mesa-glx && \
    apt-get clean && \
    virtualenv llm_py_env && pwd && ls && ls llm_py_env/bin/activate


