FROM ubuntu:24.04 as builder
#FROM llm_rag:1.1

WORKDIR /opt
ARG PROXY=""
# ARG PROXY=" -i http:///root/pypi/+simple --trusted-host devpi.11.11.77.81.nip.io"
#ARG PROXY=" -i https://pypi.tuna.tsinghua.edu.cn/simple"
RUN apt-get update && \
    apt-get -y install python3 python3-dev python3-pip virtualenv && \
    apt-get clean
RUN virtualenv llm_py_env && pwd && ls && ls llm_py_env/bin/activate
# 确保 当前目录下的 ./llm_py_env_whl.Python.3.12.3 存在，且whl离线包与当前python的版本完全一致, 离线安装时使用
COPY ./llm_py_env_whl.Python.3.12.3 /tmp/whl
RUN ./llm_py_env/bin/pip install --no-cache-dir --no-index --find-links=/tmp/whl gunicorn \
    langgraph langchain_ollama langchain_openai langchain_community \
    langchain langchain_huggingface langchain_text_splitters langchain_huggingface langchain_unstructured unstructured \
    unstructured[pdf] langchain_core flask pydantic python-docx nltk sentence-transformers faiss_cpu torch \
    concurrent_log_handler pymysql cx_Oracle sounddevice pydub pycryptodome wheel qrcode[pil] lxml $PROXY && \
    rm -rf /tmp/whl && \
    rm -rf ~/.cache/pip


FROM ubuntu:24.04
RUN apt-get update && \
    apt-get -y install python3 python3-pip && \
    apt-get clean
COPY --from=builder /opt/llm_py_env /opt/llm_py_env
RUN bash -c 'ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime' && \
    ulimit -n 65535
WORKDIR /opt/app
EXPOSE 19000
ENTRYPOINT ["sh", "./start_rag.sh"]
