create table stu(name varchar(10),code varchar(10),subject varchar(10), score number(16,2));
INSERT INTO stu (name, code, subject, score)  VALUES ('张三', 'S001', '数学', 95.50);
commit;

--------------------------------------------------------
--  DDL for Table ORDER_INFO
--------------------------------------------------------

  CREATE TABLE "TEST"."ORDER_INFO"
   (	"ID" NUMBER,
	"订单ID" NUMBER,
	"省" VARCHAR2(32 BYTE),
	"公司名称" VARCHAR2(128 BYTE),
	"商品名称" VARCHAR2(128 BYTE),
	"年" NUMBER,
	"创建时间" VARCHAR2(64 BYTE),
	"支付方式" VARCHAR2(64 BYTE),
	"支付金额" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "TEST"."ORDER_INFO"  IS '燃气销售经营信息表';
--------------------------------------------------------
--  DDL for Index SYS_C006995
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C006995" ON "TEST"."ORDER_INFO" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDER_INFO
--------------------------------------------------------

  ALTER TABLE "TEST"."ORDER_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TEST"."ORDER_INFO" MODIFY ("订单ID" NOT NULL ENABLE);


CREATE TABLE order_info ( id NUMBER PRIMARY KEY, "订单ID" NUMBER NOT NULL,省 VARCHAR2(32), 公司名称 VARCHAR2(128),  商品名称 VARCHAR2(128),  年 NUMBER,   创建时间 VARCHAR2(64), 支付方式 VARCHAR2(64), 支付金额 VARCHAR2(64));

CREATE SEQUENCE order_info_seq START WITH 3 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER order_info_trigger BEFORE INSERT ON order_info FOR EACH ROW BEGIN  :new.id := order_info_seq.NEXTVAL; END;